version: '3'

volumes:
  web_data:

services:
  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./web:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - v2ray
  v2ray:
    build:
      context: .
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./config:/etc/v2ray
      - ./certs:/certs
      - ./logs/v2ray:/var/log/v2ray
    environment:
      - V2RAY_DOMAIN=${DOMAIN:-example.com}
    depends_on:
      - acme
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:443" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
      
  acme:
    image: neilpang/acme.sh:latest
    restart: "no"
    volumes:
      - ./acme:/acme.sh
      - ./certs:/certs
    environment:
      - CF_Token=${CF_TOKEN}
      - CF_Account_ID=${CF_ACCOUNT_ID}
      - CF_Zone_ID=${CF_ZONE_ID}
      - DOMAIN=${DOMAIN:-example.com}
      - CF_Email=${CF_EMAIL}
    command: >
      --issue 
      --dns dns_cf 
      -d ${DOMAIN:-example.com}
      --key-file /certs/private.key
      --cert-file /certs/cert.crt
      --fullchain-file /certs/fullchain.crt
      --server letsencrypt